[project]
name = "midi-visualiser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "mido>=1.3.3",
    "pygame>=2.6.1",
]
